version: '2.1'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB:       "ostock_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: "S9HP4v88kDuFFzh9DSQB"
    networks:
      backend:
        aliases:
          - "configserver"
  licensingservice:
    image: licensing-service:0.0.2-SNAPSHOT
    environment:
      spring.cloud.config.uri: http://configserver:8071
      spring.cloud.config.fail-fast: "true"
      spring.cloud.config.retry.max-attempts: 5
      spring.cloud.config.retry.initial-interval: 1500
      spring.cloud.config.retry.multiplier: 1.5
      spring.datasource.password: "RLfepWQZUngNgxDmSB89"
      PROFILE: "dev"
      ENCRYPT_KEY: "S9HP4v88kDuFFzh9DSQB"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge